[package]
name = "TPRL"
version = "0.1.0"
edition = "2024"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[dependencies]
clearscreen = "4.0.2"
crossterm = "0.29.0"
serde_json = "1.0.141"
BTMD = { path = "BTMD" }