[package]
name = "TPRL"
version = "0.1.0"
edition = "2024"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[dependencies]
ansi-parser = "0.9.1"
clearscreen = "4.0.2"
crossterm = "0.29.0"
figlet-rs = "0.1.5"
serde = "1.0.219"
serde_json = "1.0.141"
